### ISSUE TITLE
keep getting same error message 'MissingSchema'

### ISSUE THREAD

**Issue by chBAco** [traveltime-dev/traveltime-platform-qgis-plugin#45]
I'm using the TT plugin in QGIS. I keep receiving the same error message when I try to create travel isochrones. The plugin used to work for me, but have been having this problem for several days now. Can anyone help? thx 

Traceback (most recent call last):
File "/Users/charliecouve/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/base.py", line 107, in processAlgorithm
return self.doProcessAlgorithm(parameters, context, feedback)
File "/Users/charliecouve/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/advanced.py", line 489, in doProcessAlgorithm
response_data = self.processAlgorithmMakeRequest(
File "/Users/charliecouve/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/base.py", line 224, in processAlgorithmMakeRequest
request = requests.Request(
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/requests/models.py", line 257, in prepare
p.prepare(
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
self.prepare_url(url, params)
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/v4/time-map': No schema supplied. Perhaps you meant http:///v4/time-map?

Execution failed after 0.21 seconds

**Comment by olivierdalang** [comment]
@chBAco Did you maybe change the endpoint in the settings by mistake ? Open the plugin settings and make sure you have `https://api.traveltimeapp.com` in the `Customize endpoint` input. Please reopen this if that does not fix it.
